{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
  {{- with .Values.metadata.labels }}
    {{- toYaml .Values.metadata.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.metadata.annotations }}
  annotations:
    {{- toYaml .Values.metadata.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if eq .Values.deployment.strategy "RollingUpdate" }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
  {{- else }}
  strategy:
    type: {{ .Values.deployment.strategy }}
  {{- end }}
  # replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      {{- if and .Values.template.metadata .Values.template.metadata.annotations }}
      annotations:
        {{- toYaml .Values.template.metadata.annotations | nindent 4 }}
      {{- end }}
    spec:      
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        {{- if .Values.spec.resources }}
        resources:
        {{- toYaml .Values.spec.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.spec.readinessProbe }}
        readinessProbe:
        {{- toYaml .Values.spec.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.spec.livenessProbe }}
        livenessProbe:
        {{- toYaml .Values.spec.livenessProbe | nindent 10 }}
        {{- end }}
{{- end }}