apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
{{- with .Values.metadata.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.metadata.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:      
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
{{- if .Values.spec.resources }}
          resources:
{{ toYaml .Values.spec.resources | indent 12 }}
{{- end }}
{{- if .Values.spec.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.spec.readinessProbe | indent 12 }}
{{- end }}
{{- if .Values.spec.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.spec.livenessProbe | indent 12 }}
{{- end }}
