apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.name }}-jaeger-collector
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.jaeger.name }}-jaeger-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP
