apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.name }}-jaeger-query
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.jaeger.name }}-jaeger-query
  ports:
    - name: http
      port: 16686
      targetPort: 16686