apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otel.name }}-otel-config
  namespace: {{ .Values.namespace }}
data:
  otel-collector-config.yaml: |
    receivers:
      kubeletstats:
        collection_interval: 10s
        auth_type: serviceAccount
        endpoint: https://${KUBELET_HOST}:10250
        insecure_skip_verify: true
        metric_groups:
          - container
          - pod
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      otlp/jaeger:
        endpoint: ${env:JAEGER_ENDPOINT}
        tls:
          insecure: true
      datadog:
        api:
          site: ${env:DATADOG_ENDPOINT}
          key: ${env:DATADOG_API_KEY}
        metrics:
          resource_attributes_as_tags: true

      elasticsearch:
        endpoint: ${env:ES_ENDPOINT}
        tls:
          insecure_skip_verify: true
        api_key: ${env:ES_API_KEY}

    processors:
      k8sattributes:
        filter:
          namespace: ${env:NAMESPACE}
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.pod.start_time
        # Pod association using resource attributes and connection
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
              - from: resource_attribute
                name: k8s.pod.ip
              - from: connection
      batch:
        timeout: 5s
        send_batch_size: 512
        send_batch_max_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128

      transform/logs:
         log_statements:
         - context: log
           statements:
             - delete_key(attributes, "code.function")
             - delete_key(attributes, "code.lineno")
         - context: resource
           statements:
             - set(attributes["elasticsearch.index"], Concat(["logs", attributes["service.name"], attributes["deployment.environment.name"]], "-"))
      resource:
        attributes:
          - key: "process.pid"
            action: delete
          - key: "process.executable.path"
            action: delete
          - key: "process.command_line"
            action: delete
          - key: "process.runtime.name"
            action: delete

    extensions:
      health_check: {}

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [otlp/jaeger, datadog]
        metrics:
          receivers: [otlp, kubeletstats]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [datadog]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, transform/logs, k8sattributes, resource, batch]
          exporters: [elasticsearch]