apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otel.name }}-otel
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.otel.name }}-otel
spec:
  selector:
    app: {{ .Values.otel.name }}-otel
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: health-check
      port: 13133
      targetPort: 13133
  type: ClusterIP