{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
  strategy:
  {{- if eq .Values.rollout.strategy "canary" }}
    canary:
      steps:
      {{- range .Values.rollout.canary.steps }}
      {{ toYaml . | indent 6 }}
      {{- end }}
  {{- else if eq .Values.rollout.strategy "blueGreen" }}
    blueGreen:
      activeService: {{ .Values.rollout.blueGreen.activeService }}
      previewService: {{ .Values.rollout.blueGreen.previewService }}
      autoPromotionEnabled: {{ .Values.rollout.blueGreen.autoPromotionEnabled }}
    {{- end }}
{{- end }}
