# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: {{ .Release.Name }}
#   name: {{ .Release.Name }}
# spec:
#   selector:
#     app: {{ .Release.Name }}
#   ports:
#     - port: 80
#       targetPort: {{ .Values.port }}
#       protocol: TCP

{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "blueGreen") }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.blueGreen.activeService }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    rollout: active
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.blueGreen.previewService }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    rollout: preview
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP

{{- else }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP

{{- end }}
