deployment:
  enabled: false
env:
  application.name: invoices
  application.otel.memory-exporter: false
  color: yellow
  management.metrics.export.otlp.enabled: true
  management.tolp.metrics.export.step: 15s
  management.tracing.enabled: true
  otel.exporter.otlp.compression: gzip
  otel.exporter.otlp.endpoint: http://invoices-dev-otel.invoices-dev.svc.cluster.local:4318
image:
  pullPolicy: Always
  repository: 290780715171.dkr.ecr.us-east-1.amazonaws.com/invoices
  tag: latest-main
imagePullSecrets:
  - regcred
ingress:
  annotations:
    app_root:
      enabled: false
      value: ""
    rewrite_target:
      enabled: false
      value: /
  host: invoices-dev.devkit.kaua.info
  serviceName: keda-add-ons-http-interceptor-proxy
  tls:
    clusterIssuer: letsencrypt-prod
    enabled: false
jaeger:
  ingress:
    annotations:
      app_root:
        enabled: false
        value: ""
      rewrite_target:
        enabled: false
        value: /
    host: invoices-dev-jaeger-query.devkit.kaua.info
    tls:
      clusterIssuer: letsencrypt-prod
      enabled: false
  name: invoices-dev
  replicas: 1
  storage:
    indexPrefix: invoices-dev
    secretName: elasticsecretjaeger
    type: elasticsearch
    url: https://fdfb20f7e3f344d49681d9785183f4f7.us-east-2.aws.elastic-cloud.com:443
namespace: invoices-dev
otel:
  datadog:
    endpoint: us5.datadoghq.com
    secretName: datadogsecret
  elasticsearch:
    endpoint: https://fdfb20f7e3f344d49681d9785183f4f7.us-east-2.aws.elastic-cloud.com:443
    secretName: elasticsecret
  jaeger:
    endpoint: http://invoices-dev-jaeger-collector.invoices-dev.svc.cluster.local:4317
  name: invoices-dev
  rbac:
    clusterRoleBindingName: otel-collector-binding
    clusterRoleName: otel-collector-role
    serviceAccountName: otel-collector
  replicas: 1
port: 8080
rollout:
  canary:
    steps:
      - setWeight: 20
      - pause:
          duration: 10s
      - setWeight: 50
      - pause:
          duration: 1m
      - setWeight: 100
  enabled: true
  strategy: canary
scaledObject:
  enabled: true
  maxReplicas: 150
  minReplicas: 1
  name: invoices-dev
  scaledownPeriod: 600
  targetPort: 80
spec:
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /api/actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /api/actuator/health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
  replicas: 2
