containerPort: 8080
deployment:
  enabled: true
env:
  COLOR: YELLOW
  otel.exporter.otlp.compression: gzip
  otel.exporter.otlp.endpoint: http://localhost:4318
image:
  pullPolicy: Always
  repository: 290780715171.dkr.ecr.us-east-1.amazonaws.com/invoices
  tag: latest-develop
imagePullSecrets:
  - regcred
ingress:
  annotations:
    app_root:
      enabled: false
      value: ""
    rewrite_target:
      enabled: false
      value: /
  host: invoices-dev.devkit.kaua.info
  tls:
    clusterIssuer: letsencrypt-prod
    enabled: false
port: 8080
replicaCount: 1
rollout:
  blueGreen:
    activeService: invoices
    autoPromotionEnabled: false
    previewService: invoices-preview
  enabled: false
  strategy: blueGreen
spec:
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /api/actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /api/actuator/health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
  replicas: 1
