image:
  repository: 290780715171.dkr.ecr.us-east-1.amazonaws.com/invoices
  tag: latest-develop
imagePullSecrets:
  - regcred
ingress:
  annotations:
    app_root:
      enabled: false
      value: ""
    rewrite_target:
      enabled: false
      value: /
  host: invoices-dev.devkit.kaua.info
  tls:
    clusterIssuer: letsencrypt-prod
    enabled: false
port: 8080
spec:
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /api/actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /api/actuator/health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
  replicas: 1
